### ISSUE TITLE
Need to set redirect_uri to "postmessage" when requesting access token

### ISSUE THREAD

**Issue by json2d** [shobhitsinghal624/passport-google-authcode#9] opened 2019-02-01 22:38 UTC
Followed example boilerplate to a tee and but was getting an error response from `_exchangeAuthCode` call here:

https://github.com/shobhitsinghal624/passport-google-authcode/blob/master/lib/passport-google-authcode/strategy.js#L91

the error response:

**400 Bad Request**
```
{ 
  "error" : "missing param redirect_uri",
  "error_description" : "Bad Request"
}
```
After some googling, turns out that for this kind of serverside access token requests, the `redirect_uri` option needs to be set to `postmessage`

ref: https://stackoverflow.com/questions/44369307/redirect-uri-error-when-using-googleauth-grantofflineaccess-to-authenticate-on-s

After adding this things finally work as expected 👍

**Comment by hangctt-1528** [comment] 2019-06-12 12:29
@shobhitsinghal624 
I've encountered the same issue.
Could you review and merge this pull request?

**Comment by shobhitsinghal624** [comment] 2019-06-13 07:18
@hangctt-1528 Cannot merge the PR since hard coding `redirect_uri` will break other use cases where it is needed. A better solution is to set it manually when configuring the strategy, as shown below.

```
passport.use(new GoogleAuthCodeStrategy({
    clientID: GOOGLE_CLIENT_ID,
    clientSecret: GOOGLE_CLIENT_SECRET,
    callbackURL: 'postmessage'
  },
  function(accessToken, refreshToken, profile, done) {
    User.findOrCreate({ googleId: profile.id }, function (err, user) {
      return done(err, user);
    });
  }
));
```

Setting the `callbackURL` is pretty common in most passport strategies. This `callbackURL` gets assigned to `redirect_uri` internally.

In your specific case, the problem is that you don't really need a callback to a URL and that is why you are not setting it, which is logically correct. But, google's API expects a callbackURL and throws an error if it's not provided. So, the solution is to set it to anything that is not null and `postmessage` is a non-null value. I had it set to `https://developers.google.com/oauthplayground` in one of my projects since thats what is set in the test suite provided by google.

Ideally, I'd recommend you set it to some URL in your own domain.

Hope this helps. I'll update the README file to show how callbackURL can be set.

**Closed** 2019-07-07 11:19 UTC
